import { Category } from './types';

export const categories: Category[] = [
  {
    id: 1,
    name: "Arrays",
    iconName: "Hash",
    completedQuestions: 15,
    totalQuestions: 30,
    questions: [
      {
        id: 1,
        title: "Two Sum",
        difficulty: "Easy",
        completed: true,
        url: "https://leetcode.com/problems/two-sum/",
      },
      {
        id: 2,
        title: "Container With Most Water",
        difficulty: "Medium",
        completed: false,
        url: "https://leetcode.com/problems/container-with-most-water/",
      },
      {
        id: 3,
        title: "Trapping Rain Water",
        difficulty: "Hard",
        completed: false,
        url: "https://leetcode.com/problems/trapping-rain-water/",
      },
    ],
  },
  {
    id: 2,
    name: "Linked Lists",
    iconName: "Link",
    completedQuestions: 8,
    totalQuestions: 20,
    questions: [
      {
        id: 4,
        title: "Reverse Linked List",
        difficulty: "Easy",
        completed: true,
        url: "https://leetcode.com/problems/reverse-linked-list/",
      },
      {
        id: 5,
        title: "Add Two Numbers",
        difficulty: "Medium",
        completed: true,
        url: "https://leetcode.com/problems/add-two-numbers/",
      },
      {
        id: 6,
        title: "Merge k Sorted Lists",
        difficulty: "Hard",
        completed: false,
        url: "https://leetcode.com/problems/merge-k-sorted-lists/",
      },
    ],
  },
  {
    id: 3,
    name: "Trees",
    iconName: "TreePine",
    completedQuestions: 12,
    totalQuestions: 25,
    questions: [
      {
        id: 7,
        title: "Maximum Depth of Binary Tree",
        difficulty: "Easy",
        completed: true,
        url: "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
      },
      {
        id: 8,
        title: "Binary Tree Level Order Traversal",
        difficulty: "Medium",
        completed: false,
        url: "https://leetcode.com/problems/binary-tree-level-order-traversal/",
      },
      {
        id: 9,
        title: "Binary Tree Maximum Path Sum",
        difficulty: "Hard",
        completed: false,
        url: "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
      },
    ],
  },
  {
    id: 4,
    name: "Dynamic Programming",
    iconName: "BrainCircuit",
    completedQuestions: 5,
    totalQuestions: 35,
    questions: [
      {
        id: 10,
        title: "Climbing Stairs",
        difficulty: "Easy",
        completed: true,
        url: "https://leetcode.com/problems/climbing-stairs/",
      },
      {
        id: 11,
        title: "Coin Change",
        difficulty: "Medium",
        completed: false,
        url: "https://leetcode.com/problems/coin-change/",
      },
      {
        id: 12,
        title: "Edit Distance",
        difficulty: "Hard",
        completed: false,
        url: "https://leetcode.com/problems/edit-distance/",
      },
    ],
  },
  {
    id: 5,
    name: "Graphs",
    iconName: "GitGraph",
    completedQuestions: 7,
    totalQuestions: 22,
    questions: [
      {
        id: 13,
        title: "Number of Islands",
        difficulty: "Medium",
        completed: true,
        url: "https://leetcode.com/problems/number-of-islands/",
      },
      {
        id: 14,
        title: "Course Schedule",
        difficulty: "Medium",
        completed: false,
        url: "https://leetcode.com/problems/course-schedule/",
      },
      {
        id: 15,
        title: "Word Ladder",
        difficulty: "Hard",
        completed: false,
        url: "https://leetcode.com/problems/word-ladder/",
      },
    ],
  },
  {
    id: 6,
    name: "Binary",
    iconName: "Binary",
    completedQuestions: 4,
    totalQuestions: 15,
    questions: [
      {
        id: 16,
        title: "Number of 1 Bits",
        difficulty: "Easy",
        completed: true,
        url: "https://leetcode.com/problems/number-of-1-bits/",
      },
      {
        id: 17,
        title: "Single Number",
        difficulty: "Easy",
        completed: true,
        url: "https://leetcode.com/problems/single-number/",
      },
      {
        id: 18,
        title: "Reverse Bits",
        difficulty: "Easy",
        completed: false,
        url: "https://leetcode.com/problems/reverse-bits/",
      },
    ],
  },
];